config/routes.rb
Rails.application.routes.draw do
  
  root to: 'photos#new'
  
  resources :photos
  

end

app/models/photo.rb
class Photo < ActiveRecord::Base
  mount_uploader :photo_image, PhotoUploader
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/faces_controller.rb
class FacesController < ApplicationController

  def new
    @photo = Photo.new
  end
  
  def create
    @photo = Photo.new(photo_params)
    if @photo.save
    else
      render 'new'
    end
  end

  def photo_params
    params.require(:photo).permit(:name, :photo_imafe)
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  def new
    @photo = Photo.new
  end
  
  def create
    @photo = Photo.new(photo_params)
    if @photo.save
      redirect_to root_path
    else
      render 'new'
    end
  end

  def index
    @photos = Photo.all
  end

  def destroy
    @photo = Photo.find(params[:id])
    @photo.destroy
    redirect_to request.referrer || root_url
  end


  def photo_params
    params.require(:photo).permit(:name, :photo_image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/faces_helper.rb
module FacesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/faces/new.html.erb
<%= form_for(@photo) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>  
  <%= f.label :photo_image %>
  <%= f.file_field :photo_image %>
  <%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Facetest</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/photos/index.html.erb
<% @photos.each do | photo | %>
  <div><%= photo.name%></div>

  <div>
    <%= image_tag photo.photo_image.url %>
  </div>
  <%= link_to photos_path,photos_path %>
  <%= link_to '消去', photo, method: :delete,
                                       data: { confirm: '良いですか？' } %>
<% end %>

<p></p>
<p></p>
<p></p>
<p></p>
<p></p>
<span>リンク</span>
<%= link_to photos_path,photos_path %>
<%= link_to new_photo_path,new_photo_path %>

app/views/photos/new.html.erb
<%= form_for(@photo) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>  
  <%= f.label :photo_image %>
  <%= f.file_field :photo_image %>
  <%= f.submit %>
<% end %>

<p></p>
<p></p>
<p></p>
<p></p>
<p></p>
<span>リンク</span>
<%= link_to photos_path,photos_path %>